version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    # volumes:
    #   - ./frontend:/app
    env_file:
      # .env.dev
      .env.prod

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
        python populate_database.py &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
